### ISSUE TITLE
figures after the decimal

### ISSUE THREAD

**Issue by annamoratti** [andreaskarman/order-weight-woocommerce#1]
Hi, I can't see anymore figures after the decimal from the order page. It's been since Ott 18, 2022. Can you help me please?

**Comment by andreaskarman** [comment]
Hi @annamoratti,

Sorry for the late reply! Could you try the latest version (0.6.4) from WordPress.org, that should take care of this problem!

https://wordpress.org/plugins/woo-order-weight/
